- name: mongodb
  hosts: mongodb
  becomes: yes
  tasks:
  - name: copy mongodb repo
    ansible.builtin.repo:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo
  
  - name: install mongdb
    ansible.builtin.package:
    name: mongodb-org
    state: present
  
  - name: start and enable mongodb
    ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes
  
  - name: allow remote connections
    ansible.builtin.replace:
    path: /etc/mongod.conf
    regex: 127.0.0.1
    replace: 0.0.0.0